In [3]:
import imageMasks as im
import skimage

In [2]:
mg = im.MaskGenerator()

Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.


In [6]:
img = skimage.io.imread("../assets/people-laughing.jpg")
masks = mg.computeMasks(img)

[[[ 87 104 160]
  [ 87 104 160]
  [ 86 103 159]
  ...
  [195 131  93]
  [197 129  92]
  [196 134  97]]

 [[ 87 104 160]
  [ 87 104 160]
  [ 88 105 161]
  ...
  [193 128  88]
  [192 128  84]
  [189 130  88]]

 [[ 87 104 160]
  [ 87 104 160]
  [ 88 105 161]
  ...
  [192 123  82]
  [191 122  80]
  [191 129  88]]

 ...

 [[115  93  72]
  [119  98  79]
  [125 104  85]
  ...
  [105  66  49]
  [108  70  51]
  [104  65  48]]

 [[118  97  76]
  [120  99  78]
  [123 102  81]
  ...
  [114  73  55]
  [104  62  46]
  [105  61  48]]

 [[122 101  80]
  [122 101  80]
  [119 101  79]
  ...
  [111  70  50]
  [109  68  50]
  [106  65  47]]]
Processing 1 images
image                    shape: (447, 671, 3)         min:    0.00000  max:  255.00000  uint8
molded_images            shape: (1, 1024, 1024, 3)    min: -123.70000  max:  151.10000  float64
image_metas              shape: (1, 93)               min:    0.00000  max: 1024.00000  float64
anchors                  shape: (1, 261888, 4)        min:   -0.

In [8]:
img.shape

(447, 671, 3)

In [9]:
img[0,0,0]

87